### ISSUE TITLE
好像和FE-Harvester-studyEveryday一样呀

### ISSUE THREAD

**Issue by lzxjack** [uestcer/2023-frontend-offer-harvester#2]

**Comment by FangzhouSu** [comment]
hhh这个是我给我们小群搞得一个仓库 想跟大家一起每天打卡学习来着 但是好像群友不太乐意一起打卡orz

![image](https://user-images.githubusercontent.com/75036021/149356139-7d1dd235-54b3-4e22-bafd-6bca2298c4c3.png)

FE-Harvester-studyEveryday这个是另一个群的每日一题打卡

**Comment by FangzhouSu** [comment]
最近玩儿开源社区玩儿得有点上头 得赶紧学点东西了 玩物丧志啊！😑😑😑

**Comment by lzxjack** [comment]
哈哈~加油😆
