### ISSUE TITLE
22/1/15 学习打卡~

### ISSUE THREAD

**Issue by FangzhouSu** [uestcer/2023-frontend-offer-harvester#5]
周末继续快乐学习~🐶🐶🐶

**Comment by BinyangXie** [comment]
改过自新 弃暗投明 痛改前非 浪子回头 悬崖勒马
今天完成html和css最最最基础部分的落实
🐶🐶🐶

**Comment by FangzhouSu** [comment]
【昨日学习复盘】
![image](https://user-images.githubusercontent.com/75036021/149605690-3164e914-82dc-42b2-9815-4151b8dc496c.png)


有俩人一起打卡了 快乐😄
![image](https://user-images.githubusercontent.com/75036021/149605692-f2d22023-5503-4157-820d-5cb8770dd5fe.png)
一起冲冲冲 ！

**Comment by FangzhouSu** [comment]
> 改过自新 弃暗投明 痛改前非 浪子回头 悬崖勒马 今天完成html和css最最最基础部分的落实 🐶🐶🐶

阿滨学咋样👨‍💻👨‍💻👨‍💻👨‍💻👨‍💻
